tasks:
  - init: |
      sudo apt-get -y install flex
      git clone https://github.com/doxygen/doxygen.git
      cd doxygen
      mkdir build
      cd build
      cmake -G "Unix Makefiles" ..
      make
      sudo make install
      cd ..
      sudo apt install -y graphviz
      sudo apt-get install -y texlive-fonts-recommended
      sudo apt-get install -y texlive-fonts-extra
      sudo apt-get install -y texlive-latex-extra
  - command: |
      doxygen Doxyfile
      cd html
      python -m http.server 3000
ports:
  - port: 3000
    onOpen: open-browser